# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Open Hardware Hangprinter Build
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/HP_Build" # the subpath of your site, e.g. /blog
url: "https://domrishe.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  domrishe
# Aux links for the upper right navigation
aux_links:
  "Hangprinter.org":
    - "https://hangprinter.org/"

  "Bill of Materials":
    - "https://docs.google.com/spreadsheets/d/1GBCrcJSBDlIqsDMb5e9Cfc8VUjfFqVKrUs1FVbOx76U/edit#gid=0"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false



# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
